CREATE TABLE CART_PRODUCTS
(
	CART_ID               INTEGER,
	PRODUCT_ID            INTEGER,
	AMOUNT                INTEGER,
	PRIMARY KEY (CART_ID, PRODUCT_ID),
	FOREIGN KEY (CART_ID) REFERENCES CART(ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);